// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VrcdnManager.Data;

#nullable disable

namespace VrcdnManager.Migrations
{
    [DbContext(typeof(VrcdnDbContext))]
    [Migration("20260728022317_AddFaceRecognitionTables")]
    partial class AddFaceRecognitionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("VrcdnManager.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<byte[]>("Value")
                        .HasColumnType("BLOB")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("VrcdnManager.Models.DetectedFace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_at");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB")
                        .HasColumnName("embedding");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("photo_id");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("detected_faces", (string)null);
                });

            modelBuilder.Entity("VrcdnManager.Models.FaceLabel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confirmed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("DetectedFaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("detected_face_id");

                    b.Property<long?>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("DetectedFaceId");

                    b.HasIndex("PersonId");

                    b.ToTable("face_labels", (string)null);
                });

            modelBuilder.Entity("VrcdnManager.Models.PersonReferencePhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<long>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_id");

                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("photo_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "PhotoId")
                        .IsUnique();

                    b.ToTable("person_reference_photos", (string)null);
                });

            modelBuilder.Entity("VrcdnManager.Models.Photo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AuthorDisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("author_display_name");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_hash");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("local_path");

                    b.Property<bool>("MetadataScanned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metadata_scanned");

                    b.Property<double>("Mtime")
                        .HasColumnType("REAL")
                        .HasColumnName("mtime");

                    b.Property<string>("PlayerNames")
                        .HasColumnType("TEXT")
                        .HasColumnName("player_names");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<string>("RemoteId")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_id");

                    b.Property<string>("RemoteStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_status");

                    b.Property<string>("RemoteUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_url");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER")
                        .HasColumnName("selected");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("BLOB")
                        .HasColumnName("thumbnail");

                    b.Property<string>("UploadedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_at");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.Property<string>("WorldName")
                        .HasColumnType("TEXT")
                        .HasColumnName("world_name");

                    b.HasKey("Id");

                    b.HasIndex("LocalPath")
                        .IsUnique();

                    b.HasIndex("RemoteStatus");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("VrcdnManager.Models.RegisteredPerson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("registered_people", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
