// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VrcPhotoManager.Data;

#nullable disable

namespace VrcPhotoManager.Migrations
{
    [DbContext(typeof(VrcdnDbContext))]
    [Migration("20260812162931_AddCropRatioOverride")]
    partial class AddCropRatioOverride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("VrcPhotoManager.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<byte[]>("Value")
                        .HasColumnType("BLOB")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.AvatarRegion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AvatarCatalogId")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_catalog_id");

                    b.Property<string>("AvatarDisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_display_name");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("photo_id");

                    b.Property<DateTime>("TaggedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("tagged_at");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("avatar_regions", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.DetectedFace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_at");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB")
                        .HasColumnName("embedding");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("photo_id");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER")
                        .HasColumnName("y");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.ToTable("detected_faces", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.FaceLabel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confirmed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("DetectedFaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("detected_face_id");

                    b.Property<long?>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("DetectedFaceId");

                    b.HasIndex("PersonId");

                    b.ToTable("face_labels", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.GamelogInferredPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("photo_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("UserId");

                    b.ToTable("gamelog_inferred_players", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.KnownVrcUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.HasKey("UserId");

                    b.ToTable("known_vrc_users", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.PersonReferencePhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<long>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_id");

                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("photo_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "PhotoId")
                        .IsUnique();

                    b.ToTable("person_reference_photos", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.Photo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AuthorDisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("author_display_name");

                    b.Property<string>("AuthorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("author_id");

                    b.Property<string>("AvatarCatalogId")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_catalog_id");

                    b.Property<string>("AvatarType")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar_type");

                    b.Property<float?>("AvatarTypeConfidence")
                        .HasColumnType("REAL")
                        .HasColumnName("avatar_type_confidence");

                    b.Property<double>("CropOffsetX")
                        .HasColumnType("REAL")
                        .HasColumnName("crop_offset_x");

                    b.Property<double>("CropOffsetY")
                        .HasColumnType("REAL")
                        .HasColumnName("crop_offset_y");

                    b.Property<string>("CropRatioOverride")
                        .HasColumnType("TEXT")
                        .HasColumnName("crop_ratio_override");

                    b.Property<bool>("FacesScanned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("faces_scanned");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_hash");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("local_path");

                    b.Property<bool>("MetadataScanned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("metadata_scanned");

                    b.Property<double>("Mtime")
                        .HasColumnType("REAL")
                        .HasColumnName("mtime");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<string>("RemoteId")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_id");

                    b.Property<string>("RemoteStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_status");

                    b.Property<string>("RemoteUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_url");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER")
                        .HasColumnName("selected");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("BLOB")
                        .HasColumnName("thumbnail");

                    b.Property<string>("UploadCropMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("upload_crop_mode");

                    b.Property<string>("UploadedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_at");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.Property<string>("WorldId")
                        .HasColumnType("TEXT")
                        .HasColumnName("world_id");

                    b.Property<string>("WorldName")
                        .HasColumnType("TEXT")
                        .HasColumnName("world_name");

                    b.Property<bool>("WorldNameInferred")
                        .HasColumnType("INTEGER")
                        .HasColumnName("world_name_inferred");

                    b.HasKey("Id");

                    b.HasIndex("LocalPath")
                        .IsUnique();

                    b.HasIndex("RemoteStatus");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.PhotoPlayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<long>("PhotoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("photo_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("UserId");

                    b.ToTable("photo_players", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.RegisteredPerson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte[]>("VrcProfileThumbnail")
                        .HasColumnType("BLOB")
                        .HasColumnName("vrc_profile_thumbnail");

                    b.Property<DateTime?>("VrcProfileThumbnailFetchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("vrc_profile_thumbnail_fetched_at");

                    b.Property<string>("VrcUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("vrc_user_id");

                    b.HasKey("Id");

                    b.HasIndex("VrcUserId")
                        .IsUnique()
                        .HasFilter("vrc_user_id IS NOT NULL");

                    b.ToTable("registered_people", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.SuggestionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<float>("AvatarAffinityBoost")
                        .HasColumnType("REAL")
                        .HasColumnName("avatar_affinity_boost");

                    b.Property<float>("CoOccurrenceBoost")
                        .HasColumnType("REAL")
                        .HasColumnName("co_occurrence_boost");

                    b.Property<float>("CombinedScore")
                        .HasColumnType("REAL")
                        .HasColumnName("combined_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("DetectedFaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("detected_face_id");

                    b.Property<float>("FaceSimilarityScore")
                        .HasColumnType("REAL")
                        .HasColumnName("face_similarity_score");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<DateTime?>("OutcomeAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome_at");

                    b.Property<long>("SuggestedPersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("suggested_person_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("DetectedFaceId");

                    b.ToTable("suggestion_logs", (string)null);
                });

            modelBuilder.Entity("VrcPhotoManager.Models.VrcUserAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alias");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Alias")
                        .IsUnique();

                    b.ToTable("vrc_user_aliases", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
