// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VrcdnManager.Data;

#nullable disable

namespace VrcdnManager.Migrations
{
    [DbContext(typeof(VrcdnDbContext))]
    partial class VrcdnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("VrcdnManager.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<byte[]>("Value")
                        .HasColumnType("BLOB")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("VrcdnManager.Models.Photo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_hash");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("local_path");

                    b.Property<double>("Mtime")
                        .HasColumnType("REAL")
                        .HasColumnName("mtime");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<string>("RemoteId")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_id");

                    b.Property<string>("RemoteStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_status");

                    b.Property<string>("RemoteUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_url");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER")
                        .HasColumnName("selected");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("BLOB")
                        .HasColumnName("thumbnail");

                    b.Property<string>("UploadedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_at");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("LocalPath")
                        .IsUnique();

                    b.HasIndex("RemoteStatus");

                    b.ToTable("photos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
